obj-$(CONFIG_SDIO_DHD_CDC_WIFI_40181_MODULE) += ../../../../hardware/wifi/broadcom/drivers/ap6xxx/broadcm_40181/
obj-$(CONFIG_RTL8188EU) += ../../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU/
obj-$(CONFIG_RTL8188EU_MP) += ../../../../hardware/wifi/realtek/drivers/8188eu/rtl8xxx_EU_MP/
obj-$(CONFIG_RTL8192CU) += ../../../../hardware/wifi/realtek/drivers/8192cu/rtl8xxx_CU/
obj-$(CONFIG_RTL8192DU) += ../../../../hardware/wifi/realtek/drivers/8192du/rtl8xxx_DU/
obj-$(CONFIG_RTL8192EU) += ../../../../hardware/wifi/realtek/drivers/8192eu/rtl8192EU/
obj-$(CONFIG_AM_WIFI_SD_MMC) +=  wifi_dt.o
obj-$(CONFIG_AM_WIFI) += wifi_power.o
