obj-$(CONFIG_SDIO_DHD_CDC_WIFI_40181_MODULE) += broadcm_40181/
obj-$(CONFIG_RTL8192CU) += rtl8xxx_CU/
obj-$(CONFIG_RTL8192DU) += rtl8xxx_DU/
obj-$(CONFIG_RTL8188EU) += rtl8xxx_EU/
obj-$(CONFIG_RTL8188EU_MP) += rtl8xxx_EU_MP/
obj-$(CONFIG_AM_WIFI_SD_MMC) +=  wifi_dt.o
obj-$(CONFIG_AM_WIFI) += wifi_power.o
