 obj-$(CONFIG_AM_DIBCOM8096) += dibcom8096_fe.o

dibcom8096_fe-objs =antenna.o channel.o component_monitor.o databus.o  dib0090.o dib0090_agc_pwm.o dib0090_agc_soft.o dib0090_cal.o dib0090_efuse.o dib0090_io.o dib0090_reset.o dib7000p.o dib7000p_gpio.o\
dib7000p_io.o dib7000p_monitor.o dib7000p_power.o dib7000p_tune.o dib7090p.o dib8000p.o dib8000p_gpio.o  dib8000p_io.o\
dib8000p_monitor.o dib8000p_power.o dib8000p_tune.o dibcom_app.o dib8090p.o dibcom_demod.o DiBcom_i2c_app.o\
dibcomfrontend.o dibx000_i2c_common.o dibx090p_ctrl.o frontend.o frontend_tune.o host.o mac.o monitor_dib7000.o\
platform_dibcom.o tuner.o

EXTRA_CFLAGS += -I.
