/**
 * This file is automaticly generated by genregs.awk. Please do not edit it 
 * Base files are ../ucode/register.h ../ucode/dos_register.h 
 *   ../ucode/c_always_on_pointer.h ../ucode/m6tv_mmc.h 
 *   ../ucode/c_stb_define.h ../ucode/secure_apb.h from VLSI team
 * Tue Oct 22 15:28:48 CST 2013 
 */

#ifdef CONFIG_ARCH_MESON8
#include <mach/register_m8.h>
#else //CONFIG_ARCH_MESON8M2
#include <mach/register_m8m2.h>
#endif
