#
# Makefile for the Amlogic NAND drivers.
#
#obj-$(CONFIG_AML_NEXT_GEN_NAND)		+= phy/
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= dev/        
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= nftl/
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= ntd/
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= block/
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= phy/ 
