#
# Makefile for Amlogic LCD Drivers
#

obj-y							+= lcd_notify.o
obj-$(CONFIG_AML_TV_LCD)		+= aml_lcd.o
obj-$(CONFIG_AML_TV_LCD_V2)		+= aml_tv_lcd.o
obj-$(CONFIG_AML_TV_LCD_V2)  += aml_tv_lcd_port/
