#
# aml_nftl
#
#EXTRA_CFLAGS += -Idrivers/amlogic/nand/aml_nftl_new/nftl

obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= aml_nftl_new.o
aml_nftl_new-objs =
aml_nftl_new-objs += aml_nftl_block.o
aml_nftl_new-objs += aml_nftl_init.o
aml_nftl_new-objs += aml_nftl_hw_interface.o
